#!/bin/bash

number=0
if [[ $1 =~ ^[0-9]*$ ]]; then
    number=$1
fi

awk -v number="$number" 'BEGIN {
    srand();
    for (i = 0; i < number; i++) {
        print (10000 * rand() - 5000);
    }
}' > input_"$number".txt

exit 0