#!/bin/bash

#**************************************************************************************************
#   Project: IVS project 2 (Calculator)
#
#   File:           generate_input
#   Description:    Bash script that generates pseudo-random inputs for our mathlib profiling
#                   output is saved into a separate .txt file.
#
#   Last change:    13.04.2024
#   Date:           13.04.2024
#   Author:         Jakub Havlík (xhavlij00)
#**************************************************************************************************

number=0
if [[ $1 =~ ^[0-9]*$ ]]; then
    number=$1
fi

awk -v number="$number" 'BEGIN {
    srand();
    for (i = 0; i < number; i++) {
        print (10000 * rand() - 5000);
    }
}' > input_"$number".txt

exit 0